### ISSUE TITLE
Phân tích bài toán

### ISSUE THREAD

**Issue by ltdao-ctu** [thanhtructran2000/luanvan_tran_thanh_truc#1]
Cần xác định có bao nhiêu nhóm đối tượng sẽ sử dụng phần mềm. Chức năng của từng nhóm đối tượng.

**Comment by thanhtructran2000** [comment]
Dạ em gửi thầy bài phân tích chức năng hệ thống.
[phantichchucnang.docx](https://github.com/thanhtructran2000/luanvan_tran_thanh_truc/files/7895872/phantichchucnang.docx)

**Comment by ltdao-ctu** [comment]
> Dạ em gửi thầy bài phân tích chức năng hệ thống.
> [phantichchucnang.docx](https://github.com/thanhtructran2000/luanvan_tran_thanh_truc/files/7895872/phantichchucnang.docx)
> 

Ok, em code chức năng đầu tiên đi. Cho em chọn chức năng đầu tiên

**Comment by thanhtructran2000** [comment]
Chào thầy, em gửi bài báo cáo tiến độ.
[BaoCaoTienDoTuan7.docx](https://github.com/thanhtructran2000/luanvan_tran_thanh_truc/files/8096671/BaoCaoTienDoTuan7.docx)

**Comment by ltdao-ctu** [comment]
Ok rồi. Em nên tạo trên này từng issue dựa trên phân tích của em. Rồi báo cáo kết quả vào từng issues để thầy biết chức năng nào xong, chức năng nào đang làm
