### ISSUE TITLE
Quản lý loại xe

### ISSUE THREAD

**Issue by ltdao-ctu** [thanhtructran2000/luanvan_tran_thanh_truc#2]

**Comment by thanhtructran2000** [comment]
- Quản lý loại xe:
+ Cập nhật loại xe.
+ Xem danh sách các loại xe.
![loaixe2](https://user-images.githubusercontent.com/97965259/155661682-77769515-ef4c-463e-92e4-f5fb499e8273.png)
![looaixe1](https://user-images.githubusercontent.com/97965259/155661695-e35e378f-4eb3-4882-893c-d22916357df9.png)

**Comment by ltdao-ctu** [comment]
Chức năng nào xong thì close nhe   em
